#!/bin/bash
# Test script for terrain quality validation
# Captures screenshots at Kangaroo Point Cliffs from multiple angles

echo "=== TERRAIN QUALITY TEST ==="
echo ""
echo "Changes made:"
echo "  - Surface layer: -4m/+2m (6m) → -20m/+10m (30m)"
echo "  - Material layers adjusted for deeper range"
echo "  - Cache cleared for fresh generation"
echo ""
echo "Expected improvements:"
echo "  ✓ Cliff appears as continuous surface (not floating blocks)"
echo "  ✓ Full 20-30m vertical drop rendered"
echo "  ✓ Less blocky, more coherent geometry"
echo ""
echo "Test locations:"
echo "  1. Cliff top (-27.4796, 153.0336) - looking down"
echo "  2. Cliff face (-27.4798, 153.0334) - mid-cliff view"
echo "  3. River below (-27.4800, 153.0332) - looking up"
echo ""
echo "Instructions:"
echo "  1. Use viewer to navigate to each location"
echo "  2. Press F12 to capture screenshot"
echo "  3. Compare with reference: screenshot/Screenshot from 2026-02-17 10-07-58.png"
echo "  4. Check for continuous surface vs floating blocks"
echo ""
echo "Performance check:"
echo "  - Monitor FPS (should stay >30)"
echo "  - Watch for stuttering during movement"
echo "  - Note vertex count in logs"
echo ""
echo "Viewer running in background (PID: $1)"
echo "Close window when testing complete."
